title: My Daily Log
description: 每日工作与学习日志
remote_theme: pages-themes/hacker
url: "https://xiaoxiaoyi12.github.io"
plugins:
  - jekyll-remote-theme
show_downloads: false

collections:
  notes:
    output: true
    permalink: /notes/:name/
  readings:
    output: true
    permalink: /readings/:name/
  thoughts:
    output: true
    permalink: /thoughts/:name/

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: post
  - scope:
      path: ""
      type: "readings"
    values:
      layout: post
  - scope:
      path: ""
      type: "thoughts"
    values:
      layout: post
