title: 依人相的月光集市
description: 只在深夜营业，售卖代码与随想
remote_theme: pages-themes/hacker
url: "https://xiaoxiaoyi12.github.io"
plugins:
  - jekyll-remote-theme
show_downloads: false

collections:
  notes:
    output: true
    permalink: /notes/:name/
  readings:
    output: true
    permalink: /readings/:name/
  thoughts:
    output: true
    permalink: /thoughts/:name/

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: post
  - scope:
      path: ""
      type: "readings"
    values:
      layout: post
  - scope:
      path: ""
      type: "thoughts"
    values:
      layout: post
